services:
  frontend:
    image: ghcr.io/ammiratafabiano/food-recipes-frontend:main
    container_name: food-recipes-frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Espone il frontend sulla porta 8080 locale

  backend:
    image: ghcr.io/ammiratafabiano/food-recipes-backend:main
    container_name: food-recipes-backend
    restart: unless-stopped
    ports:
      - "3001:3000" # Porta host 3001 per evitare conflitti con pm2
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://recipes.ammiratafabiano.dev
    volumes:
      - backend-data:/app/data

volumes:
  backend-data:
    driver: local
