services:
  food-recipes-frontend:
    image: ghcr.io/ammiratafabiano/food-recipes-frontend:main
    container_name: food-recipes-frontend
    restart: unless-stopped
    ports:
      - "8080:80"

  food-recipes-backend:
    image: ghcr.io/ammiratafabiano/food-recipes-backend:main
    container_name: food-recipes-backend
    restart: unless-stopped
    ports:
      - "3010:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://recipes.ammiratafabiano.dev
    volumes:
      - backend-data:/app/data

volumes:
  backend-data:
    driver: local
